---
abstract: 'A storage class for Catalyst Authentication using RDBO'
author:
  - 'Dave O''Neill <dmo@dmo.ca>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Store-RDBO
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Authentication: 0.10006
  Catalyst::Runtime: 0
  Rose::DB::Object: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.1000
